<?php
include('cookieadminheader.php');
$result = mysql_query("SELECT * FROM tbl_coupons where status ='yes'order by id desc");
?>
<html>
<head>
<style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}


<!--tr:nth-child(even) {
    background-color: #dddddd;
}-->

</style>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#datepicker" ).datepicker({
				
         dateFormat: 'dd/mm/yy',     
            });

  } );
  </script
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>

  
  <script src="https://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.9/js/dataTables.bootstrap.min.js"></script>
  
 <script>
 $(document).ready(function() 
 {

    $('#example').DataTable(
	{
	"pageLength": 5
	});
	
	$('#example1').DataTable(
	{
	"pageLength": 5
	});
} );
</script>

</head>
<body>

<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading" align='center'><h3> No. of samrtcookie coupon generated by student </h3></div>
		<div class="panel-body">
			<div id="no-more-tables" style="padding-top:20px;">
			<table id="example" class="display" width="100%" cellspacing="0">
				<thead style="background-color:#FFFFFF;">
									
					<tr>
					<th>Sr.No.</th>
					<th>Student Name</th>
					<th>Member Id</th>
					<th>Coupon Generate Date</th>
					<th>School Id</th>
					</tr>
				</thead>
				<tbody>
					 <?php
						$i = 1;
						while ($row= mysql_fetch_array($result)){
							//echo $result['school_id'];
							//echo"nmdsnfj";
						$id=$row['Stud_Member_Id'];
						//echo "select t_complete_name where id='$id'";
						$q=mysql_query("select c.cp_gen_date, s.std_complete_name, s.std_name, s.std_Father_name, s.std_lastname from tbl_student s join tbl_coupons c on c.Stud_Member_Id=s.id  where s.id='$id'");
						$result1=mysql_fetch_array($q);
						$name=$result1['std_complete_name'];
						$fname=$result1['std_name'];
						$mname=$result1['std_Father_name'];
						$lname=$result1['std_lastname'];
						if ($name=='')
						{
							$name = $fname." ".$mname." ".$lname;
						}
						else
						{
							$name;
						}
					 ?>
						<tr>
							<td data-title="id"><?php echo $i; ?></td>
							<td data-title="name"><?php echo $name; ?></td>
							<td data-title="mem_id"><?php echo $row['Stud_Member_Id']; ?></td>
							<td data-title="date"><?php echo $row['cp_gen_date']; ?></td>
							
							<td data-title="school_id"><?php echo $row['school_id'];?></td>
						</tr>
					<?php $i++;} ?>     
				</tbody>
			</table>

			</div>
		</div>
	</div>
</div>
</body>
</html>