<?php include 'index_header.php'; ?>  

<html>
<head>
</head>
<body>
<div class="row2  bg-wht">         
	<div class="container "> 
        <div class="row">                                              
			<div class=" col-md-12  text-center" style="padding-top:25px;" >
                <div class="about-uss clearfix">
					<h2>Sponsor:</h2>
																													
<div class="student-inf clearfix">

<p> Sponsor comes into picture when the user of smart cookie specially student,
teacher parent convert their reward points into coupon to avail various
discounts on food products, travel, recharge, etc.</p>
<p>There are two coupons in the system namely smart cookie coupons and
sponsor coupons.</p>
<p>Smart cookie coupons are the one which are generated by user using rewards
points and will be redeemed at sponsor end. Sponsor will decide the discount
based upon the points.</p>
<p>Sponsor coupons are defined by sponsor for their store and the user has to
buy those coupons using reward points. Those coupons should be redeemed
at that sponsor only.</p>
<p>When the user (teacher/ student) comes with the smart cookie coupon then
the sponsor will scan the bar / QR code present on it. The entire information
of user will occur for verifying the user details. The user can either get
discount or buy the product from the vendor.</p>
<p>When user comes with sponsor coupon then the sponsor will either enter or
scan the coupon code and will accept the coupon. Then the user can avail the
service at vendor.</p>
<p>Leaderboard of top 10 students by school/college, duration, subjects name
and activity name.</p>
<p>There is the log of accepted sponsor and smart cookie coupon as well. The log
of College wise sponsor coupons is also maintained.
</p>
<p>The sponsor can set up the discount and product. Sponsor can also set
sponsor coupons.</p>
<p>The sponsors who are registered with smart cookie and those who are
suggested by the users of smart cookie are seen on the map. </p>
<p>The sponsor can edit his created profile.</p>

					</div>
				</div>
			</div>
		</div>
	</div>
</div>

</body>
</html>

<?php include 'index_footer.php'; ?>


