

<?php
include('cookieadminheader.php');
?>
<?php
if (isset($_POST['search'])) 
    {
	//datepicker,coupon_id,uname
	  $datepicker = $_POST['datepicker'];
	  $coupon_id = $_POST['coupon_id'];
	$uname = $_POST['uname'];
	
//$sqltech="SELECT tc.status,tc.coupon_id,tc.user_id,tc.amount,tc.original_point,t.t_complete_name,t.t_name,t.t_middlename,tc.issue_date,t.t_lastname FROM tbl_teacher_coupon tc join  tbl_teacher t on t.id=tc.user_id";
$sqltech="select * from tbl_coupons";	
if($coupon_id!='')
     {
		 
	$sqltech.=" where (status='p'or status='no') and  cp_code LIKE '%$coupon_id%'";
	
		 
	 }
	 
	elseif($datepicker!='')
     {
		 
	$sqltech.=" where (status='p' or status='no') and cp_gen_date='$datepicker'";	

	 }
	 elseif($datepicker!='' && $coupon_id!='')
     {
		 
	$sqltech.=" where (status='p' or status='no') and cp_gen_date='$datepicker' and cp_code LIKE '%$coupon_id%'";	

	 }
	 elseif($datepicker!='' && $uname!='')
     {
		 
	$sqltech.=" where (status='p' or status='no') and cp_gen_date='$datepicker' and stud_complete_name LIKE '%$uname%'";	

	 }
	 elseif($datepicker!='' && $uname!=''&& $coupon_id!='')
     {
		 
	$sqltech.=" where (status='p' or status='no') and tc.issue_date='$datepicker' and t.t_complete_name LIKE '%$uname%' or CONCAT(t.t_name,t.t_middlename) LIKE '%$uname%' and tc.coupon_id LIKE '%$coupon_id%'";	

	 }
	 
	 elseif($uname!='')
	 {	 
	$sqltech.=" where (status='p' or status='no') and stud_complete_name LIKE '%$uname%'";
	
		  
		 
	 }
	 elseif($uname!='' && $coupon_id!='' )
	 {	 
	$sqltech.=" where (status='p' or status='no')  and cp_code LIKE '%$coupon_id%' and stud_complete_name LIKE '%$uname%'";	 
	 }
	 
   // $row=mysql_query($sqltech);
    }
	
   else
	{
		
	//sqltech="select * from tbl_coupons where status='p' or status='no'";
		$sqltech="select * from tbl_coupons where status='p' or status='no'";

	}
	//echo $sqltech;
$row =mysql_query($sqltech);
?>
<html>
<head>
<style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

<!--tr:nth-child(even) {
    background-color: #dddddd;
}-->

</style>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#datepicker" ).datepicker({
				
         dateFormat: 'dd/mm/yy',     
            });

  } );
  </script
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>

  
  <script src="https://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.9/js/dataTables.bootstrap.min.js"></script>
  
 <script>
 $(document).ready(function() 
 {

    $('#example').DataTable(
	{
	"pageLength": 5
	});
	
	$('#example1').DataTable(
	{
	"pageLength": 5
	});
} );
</script>

</head>
<body>

		<div class="container-fluid">
<h1><center>Used Coupon Log For Student</center></h1>
		  <div class="row">
		   <form method="post">
			<div class="col-sm-3" style="background-color:lavender;">from <input type="text" id="datepicker" name="datepicker"  value="<?php if (isset($_POST['datepicker'])) {echo $_POST['datepicker'];} ?>" class="form-control">
		</div>
			<div class="col-sm-3" style="background-color:lavender;">coupon_id<input type="text" id="coupon_id" name="coupon_id" value="<?php if (isset($_POST['coupon_id'])) {echo $_POST['coupon_id'];} ?>" placeholder="coupon_id" class="form-control" >
		</div>
		 <div class="col-sm-3" style="background-color:lavender;">User name<input type="text" id="uname" name="uname" value="<?php if (isset($_POST['uname'])) {echo $_POST['uname'];} ?>"placeholder="Username" class="form-control">
		</div>
		 <div class="col-sm-3" style="background-color:lavender;">
		 <input type="submit" name="search" value="Search" class="btn btn-primary">
			</div>
			</form
		  </div>
		</div>
		 <div id="no-more-tables" style="padding-top:20px;">
	<table id="example" class="display" width="100%" cellspacing="0">
	<thead style="background-color:#FFFFFF;">
                        
		<tr>
		<th>Sr.No.</th>
		<th>Coupon</th>
		<th>Generated By</th>
		<th>Name</th>
		<th>Generated Date</th>
		<th>Original Point</th>
		<th>Status</th>
		<th>remaining Point</th>
		<th> Details</th>

		</tr>
		</thead>
	<tbody>
     <?php
	 $i = 1;
       while ($result = mysql_fetch_array($row)){
		
		//$compname=$result['t_complete_name'];	
		//$name=$result['t_name'];
		//$middlename=$result['t_middlename'];
		//$lastname=$result['t_lastname'];
		
		//if($compname=='')
		//{
		//$finalname=$name."".$middlename."".$lastname;
		//}
		//else
		//{
			$finalname=$result['t_complete_name'];
		//}
     ?>
			<tr>
			<td data-title="id"><?php echo $i; ?></td>
			<td data-title="Couponid"><?php echo $result['cp_code']; ?></td>

			<td>
			<?php echo "Student";?>
			</td>
				
			<td><?php echo $result['stud_complete_name']; ?></td>
			<td><?php echo $result['cp_gen_date']; ?></td>
			<td><?php echo $result['original_point']; ?></td>
			<td><?php

			$status=$result['status'];
			if($status==no) 
			{
				
				echo"Used";
				
			}
			 else 
			 {
				 echo"PartiallyUsed";
				 
			 }
 
 
 ?></td>
<td><?php echo $result['amount']; ?></td>
<td> <a href="Purchsed_Coupon_Details.php?coupon_id=<?php echo $result['cp_code'];?>">Show Details</td>


</tr>


</tr>
		<?php $i++;
                 }
					
                    ?>
					</thead>
 <tbody>
</table>

</div>
</body>


</html>